### ISSUE TITLE
I have got new issue

### ISSUE THREAD

**Issue by tscswcn** [bushvin/zabbix-kvm-res#7]
when using zabbix_get command to verify  in the zabbix server 

zabbix_get -s 10.120.204.101 -p 10050 -k custom.kvm.pool.size[free,VM0]
libvirt: XML-RPC error : Failed to connect socket to '/var/run/libvirt/libvirt-sock-ro': Permission denied
Traceback (most recent call last):
  File "/usr/local/bin/zabbix-kvm-res.py", line 137, in kvm_connect
    conn = libvirt.openReadOnly('qemu:///system')
  File "/usr/lib64/python3.6/site-packages/libvirt.py", line 290, in openReadOnly
    if ret is None:raise libvirtError('virConnectOpenReadOnly() failed')
libvirt.libvirtError: Failed to connect socket to '/var/run/libvirt/libvirt-sock-ro': Permission denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/zabbix-kvm-res.py", line 178, in <module>
    main()
  File "/usr/local/bin/zabbix-kvm-res.py", line 22, in main
    r = pool_free(options)
  File "/usr/local/bin/zabbix-kvm-res.py", line 112, in pool_free
    return pool_info(options)[3]
  File "/usr/local/bin/zabbix-kvm-res.py", line 126, in pool_info
    conn = kvm_connect()
  File "/usr/local/bin/zabbix-kvm-res.py", line 139, in kvm_connect
    sys.stderr.write("There was an error connecting to the local libvirt daemon using '"+uri+"'.")
NameError: name 'uri' is not defined

**Comment by tscswcn** [comment]
I have research this issue, it is caused by selinux, but  I take some action which some peaple gave, but don't take effect. I will try later.

**Comment by bushvin** [comment]
This is indeed a SElinux issue.
I have included a type enforcement file which works with CentOS/RHEL 7
Details on how to are in the README.md file
